"""
Lane Agent (Level 1 Worker)
Each intersection has 4 Lane Agents (N, S, E, W).
They track local vehicle density, wait time, and generate reasoning.
Now integrated with YOLO detection pipeline.
"""

from dataclasses import dataclass, field
from typing import Dict, Any, Optional


@dataclass
class LaneReport:
    """Report generated by a Lane Agent for the Master Agent."""
    lane: str
    density: int
    wait_time: float
    has_emergency: bool
    reasoning: str = ""
    detection_source: str = "simulation"
    vehicle_types: Dict[str, int] = field(default_factory=dict)
    has_pedestrians: bool = False


class LaneAgent:
    """
    Level 1 Agent - one per lane per intersection.
    Tracks vehicles, wait time, and emergency status.
    Generates human-readable reasoning for each decision.
    """

    def __init__(self, lane_name: str):
        self.lane_name = lane_name
        self.density: int = 0
        self.wait_time: float = 0.0
        self.has_emergency: bool = False
        self.is_green: bool = False
        self.reasoning: str = ""
        self.detection_source: str = "simulation"
        self.vehicle_types: Dict[str, int] = {}
        self.emergency_type: Optional[str] = None
        self.has_pedestrians: bool = False

    def update(
        self,
        density: int,
        has_emergency: bool,
        is_green: bool,
        dt: float = 1.0,
        detection_source: str = "simulation",
        vehicle_types: Optional[Dict[str, int]] = None,
        emergency_type: Optional[str] = None,
        detection_reasoning: str = "",
        has_pedestrians: bool = False,
    ):
        """
        Update lane state each simulation tick.
        """
        self.density = density
        self.has_emergency = has_emergency
        self.is_green = is_green
        self.detection_source = detection_source
        self.vehicle_types = vehicle_types or {}
        self.emergency_type = emergency_type
        self.has_pedestrians = has_pedestrians

        if is_green:
            self.wait_time = 0.0
        else:
            self.wait_time += dt

        # Build reasoning
        self._build_reasoning(detection_reasoning)

    def _build_reasoning(self, detection_reasoning: str = ""):
        """Generate human-readable reasoning based on current state."""
        parts = []

        # Source info
        src_label = "🎥 YOLO" if self.detection_source == "yolo" else "📊 MOCK" if self.detection_source == "mock" else "📊 SIM"
        parts.append(f"[{src_label}]")

        # Detection data
        if detection_reasoning:
            parts.append(detection_reasoning)
        else:
            parts.append(f"Observed {self.density} vehicles")
            if self.vehicle_types:
                breakdown = ", ".join(f"{v} {k}" for k, v in self.vehicle_types.items())
                parts.append(f"({breakdown})")

        # Wait time assessment
        if not self.is_green:
            if self.wait_time > 30:
                parts.append(f"⏰ CRITICAL wait: {self.wait_time:.0f}s — starvation risk!")
            elif self.wait_time > 15:
                parts.append(f"⏰ Long wait: {self.wait_time:.0f}s — requesting priority")
            elif self.wait_time > 5:
                parts.append(f"⏰ Waiting: {self.wait_time:.0f}s")

        if self.has_emergency:
            etype = self.emergency_type or "emergency vehicle"
            parts.append(f"🚨 {etype.upper()} DETECTED — maximum priority!")

        if self.has_pedestrians:
            parts.append(f"🚶 Pedestrians waiting! Priority skyrocketing.")

        trucks = self.vehicle_types.get("truck", 0)
        cars = self.vehicle_types.get("car", self.density)
        if trucks > 0:
            parts.append(f"🚚 {trucks} Trucks and 🚗 {cars} Cars detected in queue")
        
        # Current signal
        if self.is_green:
            parts.append("🟢 Currently GREEN — vehicles flowing")
        else:
            parts.append("🔴 Currently RED — vehicles stopped")

        self.reasoning = " | ".join(parts)

    def generate_report(self) -> LaneReport:
        """Generate a report for the Master Agent."""
        return LaneReport(
            lane=self.lane_name,
            density=self.density,
            wait_time=self.wait_time,
            has_emergency=self.has_emergency,
            reasoning=self.reasoning,
            detection_source=self.detection_source,
            vehicle_types=self.vehicle_types,
            has_pedestrians=self.has_pedestrians,
        )

    def to_dict(self) -> Dict[str, Any]:
        """Serialize for WebSocket broadcast."""
        return {
            "lane": self.lane_name,
            "density": self.density,
            "wait_time": round(self.wait_time, 1),
            "has_emergency": self.has_emergency,
            "is_green": self.is_green,
            "reasoning": self.reasoning,
            "detection_source": self.detection_source,
            "vehicle_types": self.vehicle_types,
            "emergency_type": self.emergency_type,
            "has_pedestrians": self.has_pedestrians,
        }
